# Changes here will be overwritten by Copier.
_commit: 1.6.1
_src_path: https://github.com/pawamoy/copier-uv.git
author_email: sgp9504@nyu.edu
author_fullname: Provost Simon
author_username: simonprovost
copyright_date: '2025'
copyright_holder: Provost Simon
copyright_holder_email: sgp9504@nyu.edu
copyright_license: MIT
insiders: false
project_description: ''
project_name: auctus_search
python_package_command_line_name: auctus-search
python_package_distribution_name: auctus-search
python_package_import_name: auctus_search
repository_name: auctus-search
repository_namespace: simonprovost
repository_provider: github.com

